config/routes.rb
Rails.application.routes.draw do
  resources :suggestions
  get 'home/index'
  get 'home/dashboard'
  get 'home/checkoutpage'
  get 'suggestions/received' => 'suggestions#received', as: 'received_suggestion'
  get 'suggestions/approve/:id' => 'suggestions#approve', as: 'approve_suggestion'
  get 'reservations/history' => 'reservations#user_history', as: 'user_history_reservation'
  get 'reservations/checkout' => 'reservations#checkout_reservation', as: 'checkout_reservation'
  get 'reservations/checkin' => 'reservations#checkin_reservation', as: 'checkin_reservation'
  get 'reservations/cancel' => 'reservations#cancel_reservation', as: 'cancel_reservation'
 # get 'reservations/new_for_user/' => 'reservations#new_for_user', as: 'new_reservation_for_user'
 # get 'reservations/create_for_user' => 'reservations#create_for_user', as: 'create_reservation_for_user'

  resources :reservations
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'registrations'
		
      }
      devise_scope :user do
      	get "users/display", to: "registrations#display", as: "user_display"
        get "user/new1", to: "registrations#new1", as: "user_new1"
        get "user/edituser", to: "registrations#edituser", as: "edituser"
        post "user/create_user", to: "registrations#create_user", as: "create_new_user"
        get "user/show", to: "registrations#show", as: "showuser"
      end

  resources :cars
  get 'cars/:id/notify' => 'cars#notify_availability', as: 'notify_availability'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if user_signed_in?
      redirect_to home_dashboard_path
    end
  end

  def dashboard

    @res=Reservation.where(current: true)
    if( @res != nil)
    @res.each do |resr|
      if resr.checkout+30.minutes<Time.now
        user=User.find(resr.user_id)
        resr.checkin=resr.checkout+30.minutes
        resr.current=false
        resr.save!
        @car=Car.find(resr.car_id)
        @user=User.find(resr.user_id)
        @car.status="AVAILABLE"
        @car.save!
        QMailMailer.timeout_email(@user).deliver_now

      end
    end
      end
  end

  def checkoutpage
 	@time=current_user.reservations.last.checkout
 	if(@time>Time.now && @time<Time.now+30.minutes)
 			render :template=>"home/checkoutpage.html.erb"
 	else
 		flash[:error] = 'Your checkout is not ready as yet.'
 		render :template=>"home/dashboard" ,:locals=>{:msg=>"jk"}
 		
 		
 	end

  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_current_reservation.html.erb
<%  if current_user.reservations.count != 0 %>
    <% if current_user.reservations.last != nil%>
        <% @current_reservation = current_user.reservations.last %>
        <% if @current_reservation.current %>
            <% @current_car = Car.find(@current_reservation.car_id)%>
            <h2> Current Booking </h2>
            <p>
              <strong>CAR ID:</strong>
              <%= @current_car.model %>
            </p>
            <p>
              <strong>CHECK OUT:</strong>
              <%= @current_reservation.checkout %>
            </p>
            <p>
              <strong>HOURS:</strong>
              <%= @current_reservation.hours %>
            </p>
            <%= link_to "Checkout", checkout_reservation_path(@current_reservation)%>
            <%= link_to "Cancel booking", cancel_reservation_path(@current_reservation)%>
            <%= link_to "Checkin", checkin_reservation_path(@current_reservation)%>
        <%end%>
    <% end %>
<%end%>

app/views/home/checkoutpage.html.erb
<p>Your car has been checked out. Enjot your ride.</p>

<%= link_to "DASHBOARD", home_dashboard_path %>

app/views/home/dashboard.html.erb
<h1> DASHBOARD </h1>
<%= render 'current_reservation' %>

<% if current_user.role == 'customer' %>
<h3><%= link_to "Search Cars" , cars_path %></h3>
<br>
<h3><%= link_to "Your Past Reservations" , user_history_reservation_path(current_user) %> </h3>
<br>
<h3><%= link_to "Suggest A Car" , new_suggestion_path %> </h3>
<br>
<% end -%>
<% if current_user.role != 'customer' %>
  
  <h3><%= link_to "Manage Users" , user_display_path %></h3>
  <br>
  <h3><%= link_to "Manage Cars" , cars_path %></h3>
  <br>
  <h3><%= link_to "Manage Reservations" , reservations_path %></h3>
  <br>
  <h3><%= link_to "Manage Suggestions" , suggestions_path %></h3>


<% end -%>

app/views/home/index.html.erb
<h1>CAR RENTAL APPLICATION</h1>

<ul>
		<p>You need to register before booking cars.</p>
		<%= link_to "Sign Up", new_user_registration_path, :class=>'btn btn-large btn-default' %>
		
		<br><br>
		<%= link_to "Sign In", new_user_session_path,:class=>'btn btn-large btn-default' %>
</ul>