config/routes.rb
Rails.application.routes.draw do
  resources :suggestions
  get 'home/index'
  get 'home/dashboard'
  get 'home/checkoutpage'
  get 'suggestions/received' => 'suggestions#received', as: 'received_suggestion'
  get 'suggestions/approve/:id' => 'suggestions#approve', as: 'approve_suggestion'
  get 'reservations/history' => 'reservations#user_history', as: 'user_history_reservation'
  get 'reservations/checkout' => 'reservations#checkout_reservation', as: 'checkout_reservation'
  get 'reservations/checkin' => 'reservations#checkin_reservation', as: 'checkin_reservation'
  get 'reservations/cancel' => 'reservations#cancel_reservation', as: 'cancel_reservation'
 # get 'reservations/new_for_user/' => 'reservations#new_for_user', as: 'new_reservation_for_user'
 # get 'reservations/create_for_user' => 'reservations#create_for_user', as: 'create_reservation_for_user'

  resources :reservations
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'registrations'
		
      }
      devise_scope :user do
      	get "users/display", to: "registrations#display", as: "user_display"
        get "user/new1", to: "registrations#new1", as: "user_new1"
        get "user/edituser", to: "registrations#edituser", as: "edituser"
        post "user/create_user", to: "registrations#create_user", as: "create_new_user"
        get "user/show", to: "registrations#show", as: "showuser"
      end

  resources :cars
  get 'cars/:id/notify' => 'cars#notify_availability', as: 'notify_availability'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/car.rb
class Car < ApplicationRecord
	validates :rate ,presence:true, numericality: {only_float: true}
	validates :model, format: { with: /\A[a-zA-Z]+\z/, message: "allows only letters" }
	validates :license, length: { is: 7 }, uniqueness: true
	validates :manufacturer, format: { with: /\A[a-zA-Z]+\z/, message: "allows only letters" }
	validates :style, inclusion: { in: ['Hatchback', 'Sedan', 'SUV'], message: "Style is not Hatchback, Sedan or SUV" }
	validates :status, inclusion: { in: ['RESERVED', 'CHECKEDOUT', 'AVAILABLE'], message: "Status is not CHECKEDOUT, RESERVED  or AVAILABLE" }
  validates :location ,presence: true
	has_many :reservations
	has_many :users, through: :reservations
	has_many :subscriptions
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy, :notify_availability]
  # GET /cars
  # GET /cars.json
  def index
    @searchflag=1
    if(params[:flag])
      @searchflag=0
    end
    if @searchflag == 0
      @cars = Car.where("location LIKE CASE WHEN ? = ''  THEN '%' ELSE ? END AND model LIKE CASE WHEN ? = ''  THEN '%' ELSE ? END AND manufacturer LIKE CASE WHEN ? = ''  THEN '%' ELSE ? END ", params[:location],params[:location], params[:model],params[:model], params[:manufacturer],params[:manufacturer])
    else 
      @cars =Car.all
    end

    if (current_user.reservations.count == 0)
        @allow_booking = true
    elsif (current_user.reservations.last.current == false)
        @allow_booking = true
    else
        @allow_booking = false
    end

  end

  # GET /cars/1
  # GET /cars/1.json
  def show
   # @car = Car.find(params[:id])
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
   # @car = Car.find(params[:id])
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    #@car = Car.find(params[:id])
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    #@car = Car.find(params[:id])
    if (@car.reservations.count != 0)
      if(@car.reservations.last.current == true)
        respond_to do |format|
          if (@car.status == 'CHECKEDOUT')
          format.html { redirect_to cars_url, notice: 'Car is checkedout. Cant be destroyed' }
          format.json { head :no_content }
          else
            format.html { redirect_to cars_url, notice: 'Car is reserved. Cant be destroyed' }
            format.json { head :no_content }
          end

        end
        return
      end
    end
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def notify_availability
    #@car = Car.find(params[:format])
    @notif= Subscription.new
    @notif.user_id = current_user.id
    @notif.car_id = params[:id]
    @notif.notified=false
    if @notif.save!
   # @car = Car.find(params[:id])
    redirect_to cars_url, notice: 'You will recieve notification when Car : '+ @car.model + ' is available on your register email'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find_by_id(params[:id])
     end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:model, :manufacturer, :license, :rate, :location, :style, :status)
    end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<%= form_with(model: car, local: true) do |form| %>
  <% if car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :model %>
    <% if params[:suggestion]  %>
    <%= form.text_field :model, id: :car_model, value: params[:model] %>
    <% else %>
    <%= form.text_field :model, id: :car_model%>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :manufacturer %>
    <% if params[:suggestion]  %>
    <%= form.text_field :manufacturer, id: :car_manufacturer, value: params[:manufacturer]%>
    <% else %>
    <%= form.text_field :manufacturer, id: :car_manufacturer %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :license %>
    <%= form.text_field :license, id: :car_license %>
  </div>

  <div class="field">
    <%= form.label :rate %>
    <%= form.number_field :rate, id: :car_rate %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <% if params[:suggestion]  %>
    <%= form.text_field :location, id: :car_location, value: params[:location] %>
    <% else %>
    <%= form.text_field :location, id: :car_location %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :style %>
    <% if params[:suggestion]  %>
    <%= form.text_field :style, id: :car_style , value: params[:style] %>
    <% else %>
    <%= form.text_field :style, id: :car_style %>
    <%end %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status, id: :car_status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cars</h1>
<br>
<% if current_user.role != 'customer' %>

  <%= link_to 'ADD NEW CAR', new_car_path,:class=>'btn btn-large btn-primary' %>
<% end -%>
<br>
<br>




<br>

<%= form_tag(cars_path, method: "get") do %>
    <%= label_tag(:location, "location") %>
    <%= text_field_tag(:location) %>
    <%= label_tag(:model, "model") %>
    <%= text_field_tag(:model) %>
    <%= label_tag(:manufacturer, "manufacturer") %>
    <%= text_field_tag(:manufacturer) %>
    <%= hidden_field_tag(:flag , true) %>
    <%= submit_tag("Search") %>
<% end %>

<div class="table-responsive">
  <table class="table table-striped ">

  <thead>
  <tr>
    <th>Model</th>
    <th>Manufacturer</th>
    <th>License</th>
    <th>Rate</th>
    <th>Location</th>
    <th>Style</th>
    <% if current_user.role != 'customer' %>
    <th>Status</th>
    <% end -%>
    <th colspan="5"></th>
  </tr>
  </thead>
  <tbody>
    <% @cars.each do |car| %>
    <tr>
      <td><%= car.model %></td>
      <td><%= car.manufacturer %></td>
      <td><%= car.license %></td>
      <td><%= car.rate %></td>
      <td><%= car.location %></td>
      <td><%= car.style %></td>
      <td><%= car.status %></td>
      <% if current_user.role == 'customer' && @allow_booking == true %>
      <td><%= link_to 'Reserve', new_reservation_path(:car_id => car.id), data: { confirm: 'Are you sure?' }, :class=>'btn btn-large btn-success' %></td>
          <% if car.status != 'AVAILABLE'%>
          <td><%= link_to 'notify_availability', notify_availability_path(car), :class=>'btn btn-large btn-primary'%></td>
          <% end %>
      <% end -%>
      <% if current_user.role != 'customer' %>
          <td><%= link_to 'Show', car, :class=>'btn btn-large btn-primary'  %></td>
          <td><%= link_to 'Edit', edit_car_path(car), :class=>'btn btn-large btn-warning' %></td>
          <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' }, :class=>'btn btn-large btn-danger' %></td>
          <br>
      <% end %>
    </tr>

    <% end %>
  </tbody>
</table>
</div>


<%= link_to 'DASHBOARD', home_dashboard_path,:class=>'btn btn-large btn-primary' %>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<div class="table-responsive">
  <table class="table table-striped">
    <tbody>
      <tr>
        <th>Model:</th>
          <td><%= @car.model %></td>
      </tr>
      <tr>
        <th>Manufacturer:</th>
        <td><%= @car.manufacturer %></td>
      </tr>
      <tr>
        <th>License:</th>
        <td><%= @car.license %></td>
      </tr>
      <tr>
        <th>Rate:</th>
        <td><%= @car.rate %></td>
      </tr>
      <tr>
        <th>Location:</th>
        <td><%= @car.location %></td>
      </tr>
      <tr>
        <th>Style:</th>
        <td><%= @car.style %></td>
      </tr>
      <tr>
        <th>Status:</th>
        <td><%= @car.status %></td>
      </tr>
    </tbody>
  </table>
  
</div>





<%= link_to 'Edit', edit_car_path(@car), :class=>'btn btn-large btn-warning' %> 
<%= link_to 'Back', cars_path, :class=>'btn btn-large btn-primary' %>