config/routes.rb
Rails.application.routes.draw do
  resources :suggestions
  get 'home/index'
  get 'home/dashboard'
  get 'home/checkoutpage'
  get 'suggestions/received' => 'suggestions#received', as: 'received_suggestion'
  get 'suggestions/approve/:id' => 'suggestions#approve', as: 'approve_suggestion'
  get 'reservations/history' => 'reservations#user_history', as: 'user_history_reservation'
  get 'reservations/checkout' => 'reservations#checkout_reservation', as: 'checkout_reservation'
  get 'reservations/checkin' => 'reservations#checkin_reservation', as: 'checkin_reservation'
  get 'reservations/cancel' => 'reservations#cancel_reservation', as: 'cancel_reservation'
 # get 'reservations/new_for_user/' => 'reservations#new_for_user', as: 'new_reservation_for_user'
 # get 'reservations/create_for_user' => 'reservations#create_for_user', as: 'create_reservation_for_user'

  resources :reservations
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'registrations'
		
      }
      devise_scope :user do
      	get "users/display", to: "registrations#display", as: "user_display"
        get "user/new1", to: "registrations#new1", as: "user_new1"
        get "user/edituser", to: "registrations#edituser", as: "edituser"
        post "user/create_user", to: "registrations#create_user", as: "create_new_user"
        get "user/show", to: "registrations#show", as: "showuser"
      end

  resources :cars
  get 'cars/:id/notify' => 'cars#notify_availability', as: 'notify_availability'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/suggestion.rb
class Suggestion < ApplicationRecord
#	validates :suggestion, presence:true
	validates :model, format: { with: /\A[a-zA-Z]+\z/, message: "allows only letters" }
	validates :manufacturer, format: { with: /\A[a-zA-Z]+\z/, message: "allows only letters" }
	validates :style, inclusion: { in: ['Hatchback', 'Sedan', 'SUV'], message: "Style is not Hatchback, Sedan or SUV" }
	validates :location ,presence: true
	belongs_to :user
end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController
  before_action :set_suggestion, only: [:show, :edit, :update, :destroy]

  # GET /suggestions
  # GET /suggestions.json
  def index
    @suggestions = Suggestion.all
  end

  # GET /suggestions/1
  # GET /suggestions/1.json
  def show
    @suggestion=Suggestion.find_by_id(params[:id])
  end

  # GET /suggestions/new
  def new
    @suggestion = current_user.suggestions.build()
  end

  # GET /suggestions/1/edit
  def edit
  end


  # POST /suggestions
  # POST /suggestions.json
  def create
    @suggestion = current_user.suggestions.new(suggestion_params)
    @suggestion.accepted = false
    respond_to do |format|
      if @suggestion.save
        format.html { redirect_to home_dashboard_path, notice: 'Suggestion was successfully created.' }
        format.json { render home_dashboard_path, status: :created, location: @suggestion }
      else
        format.html { render :new }
        format.json { render json: @suggestion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /suggestions/1
  # PATCH/PUT /suggestions/1.json
  def update
    respond_to do |format|
      if @suggestion.update(suggestion_params)
        format.html { redirect_to @suggestion, notice: 'Suggestion was successfully updated.' }
        format.json { render :show, status: :ok, location: @suggestion }
      else
        format.html { render :edit }
        format.json { render json: @suggestion.errors, status: :unprocessable_entity }
      end
    end
  end

  def approve
    @suggestion = Suggestion.find(params[:id])
    if (@suggestion.accepted == false)
    @suggestion.accepted = true
    @suggestion.save!
    redirect_to new_car_path(:suggestion => true, :location => @suggestion.location, :model => @suggestion.model, :manufacturer => @suggestion.manufacturer, :style => @suggestion.style), notice: 'Suggestion was successfully accepted.'
    else
      redirect_to suggestions_path, notice: 'Already approved'
    end

  end

  # DELETE /suggestions/1
  # DELETE /suggestions/1.json
  def destroy
    @suggestion.destroy
    respond_to do |format|
      format.html { redirect_to suggestions_url, notice: 'Suggestion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_suggestion
      # @suggestion = Suggestion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def suggestion_params
      params.require(:suggestion).permit(:suggestion, :model, :manufacturer, :style, :location)
    end
end

app/helpers/suggestions_helper.rb
module SuggestionsHelper
end

app/views/suggestions/_form.html.erb
<%= form_with(model: suggestion, local: true) do |form| %>
  <% if suggestion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(suggestion.errors.count, "error") %> prohibited this suggestion from being saved:</h2>

      <ul>
      <% suggestion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <div class="field">
      <%= form.label :model %>
      <%= form.text_field :model, id: :car_model %>
    </div>

    <div class="field">
      <%= form.label :manufacturer %>
      <%= form.text_field :manufacturer, id: :car_manufacturer %>
    </div>

    <div class="field">
      <%= form.label :location %>
      <%= form.text_field :location, id: :car_location%>
    </div>

    <div class="field">
      <%= form.label :style %>
      <%= form.text_field :style, id: :car_style %>
    </div>

  <div class="field">
    <%= form.label :suggestion  %>
    <%= form.text_area :suggestion, id: :suggestion_suggestion %>
  </div>

 <!--  <div class="field">
    <%= form.label :accepted %>
    <%= form.check_box :accepted, id: :suggestion_accepted %>
  </div> -->

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/suggestions/edit.html.erb
<h1>Editing Suggestion</h1>

<%= render 'form', suggestion: @suggestion %>

<%= link_to 'Show', @suggestion %> |
<%= link_to 'Back', suggestions_path %>

app/views/suggestions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Suggestions</h1>

<div class="table-responsive">
<table class="table table-striped ">

  <thead>
    <tr>
      <th>Suggestion</th>
      <th>Accepted</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @suggestions.each do |suggestion| %>
      <tr>
        <td><%= suggestion.suggestion %></td>
        <td><% if suggestion.accepted == false %>
              Pending
            <% else %>
              Approved
            <% end -%>
        </td>
        <td><%= link_to 'Show', suggestion, :class=>'btn btn-large btn-primary' %></td>

        <td><%= link_to 'approve', approve_suggestion_path(suggestion.id), :class=>'btn btn-large btn-warning' %></td>
        <% if current_user.role == "superadmin" %>
        <td><%= link_to 'Destroy', suggestion, method: :delete, data: { confirm: 'Are you sure?' },  :class=>'btn btn-large btn-danger' %></td>

        <% end %>

      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<%= link_to 'Dashboard', home_dashboard_path, :class=>'btn btn-large btn-primary' %>

app/views/suggestions/new.html.erb
<h1>New Suggestion</h1>

<%= render 'form', suggestion: @suggestion %>

<%= link_to 'Back', home_dashboard_path %>

app/views/suggestions/received.html.erb
<h3> Your suggestion has been sent to the admin. </h3>

<%= link_to "Dashboard" , home_dashboard_path %>

app/views/suggestions/show.html.erb
<p id="notice"><%= notice %></p>
<% if current_user.role == "customer" %>
	<p>Your suggestion has been sent to the admin</p>
<% end -%>

	<tr>
        <th>Suggestion:</th>
          <td><%= @suggestion.suggestion %></td>
      </tr>
	<tr>
        <th>Model:</th>
          <td><%= @suggestion.model %></td>
      </tr>
      <tr>
        <th>Manufacturer:</th>
        <td><%= @suggestion.manufacturer %></td>
      </tr>
      <tr>
        <th>Location:</th>
        <td><%= @suggestion.location %></td>
      </tr>
      <tr>
        <th>Style:</th>
        <td><%= @suggestion.style %></td>
      </tr>


<%= link_to 'Back', suggestions_path %>

<% if current_user.role == "customer" %>
	<%= link_to 'Dashboard', home_dashboard_path %>
<% end -%>