config/routes.rb
Rails.application.routes.draw do
  resources :suggestions
  get 'home/index'
  get 'home/dashboard'
  get 'home/checkoutpage'
  get 'suggestions/received' => 'suggestions#received', as: 'received_suggestion'
  get 'suggestions/approve/:id' => 'suggestions#approve', as: 'approve_suggestion'
  get 'reservations/history' => 'reservations#user_history', as: 'user_history_reservation'
  get 'reservations/checkout' => 'reservations#checkout_reservation', as: 'checkout_reservation'
  get 'reservations/checkin' => 'reservations#checkin_reservation', as: 'checkin_reservation'
  get 'reservations/cancel' => 'reservations#cancel_reservation', as: 'cancel_reservation'
 # get 'reservations/new_for_user/' => 'reservations#new_for_user', as: 'new_reservation_for_user'
 # get 'reservations/create_for_user' => 'reservations#create_for_user', as: 'create_reservation_for_user'

  resources :reservations
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'registrations'
		
      }
      devise_scope :user do
      	get "users/display", to: "registrations#display", as: "user_display"
        get "user/new1", to: "registrations#new1", as: "user_new1"
        get "user/edituser", to: "registrations#edituser", as: "edituser"
        post "user/create_user", to: "registrations#create_user", as: "create_new_user"
        get "user/show", to: "registrations#show", as: "showuser"
      end

  resources :cars
  get 'cars/:id/notify' => 'cars#notify_availability', as: 'notify_availability'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cars</title>
    <%= csrf_meta_tags %>

   

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <div style=" float: right ">
  <% if user_signed_in? %>
    <%= link_to "Logout", destroy_user_session_path, method: :delete %>
  <% end %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </div>

  </head>

  <body>
  <!-- <p class="notice"><%= notice %></p> -->
  <div class="navbar navbar-default ">
     <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapibleMenu">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="#" class="navbar-brand">Car Rental Application</a>
      </div>
      
    <div class="collapse navbar-collapse" id="collapibleMenu">
      <ul class="nav navbar-nav navbar-right" style="color: black; margin-right: 10px">
      <li><%= link_to "Home", home_index_path %></li>
      <% if user_signed_in? %>
      <li><%= link_to "Dashboard", home_dashboard_path%></li>
      <li><%= link_to "Cars" , cars_path %></li>
      <% if current_user.role == 'superadmin' %>
        <li><%= link_to "+1 Car", new_car_path %></li>
        <li><%= link_to "Users",user_display_path %></li>
        <li><%= link_to "Reservations", reservations_path %></li>
        <li> <%= link_to "User Suggestions",suggestions_path %> </li>

      <% end -%>
      <li><%= link_to "My Profile", showuser_path(current_user) %> </li>
      <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
      <% end %>
      <%if !user_signed_in? %>
      <li><%= link_to "Sign In", new_user_session_path %></li>
      <% end %>
      </ul>
    </div>
    </div>
  </div>
  
  <%#= link_to "Home", home_index_url %>
  <div class="container">
    <p class="alert"><%= alert %></p>
    <p id="notice"><%= notice %></p>
    <%= yield %>  
  </div>
  
  </body>
</html>